#!/bin/bash

# checkout main
git checkout main
git fetch origin

echo "Pruning origin"
git remote prune origin

echo "The followin local branches are fully merged and will be removed: "
git branch --merged main | grep -v 'main$'

OPTIONS="y Y yes YES"

read -p "Delete all local merged branches? "
if [[ $OPTIONS =~ $REPLY ]]
then
    echo "Trying to remove local branches ..."
    # remove local branches
    git branch --merged main | grep -v 'main' | xargs git branch -d
    echo "Local Branches Removed"
fi

