#!/bin/bash

# Setup bash
ln -sf {~/.dotfiles/,~/.}/bashrc
sudo ln -sf ~/.dotfiles/sys_bashrc /etc/bashrc

# Setup vim
ln -sf {~/.dotfiles/,~/.}/vimrc
ln -sf {~/.dotfiles/,~/.}/gvimrc

# Setup screen
sudo ln -sf ~/.dotfiles/sys_screenrc /etc/screenrc

# Setup tmux
ln -sf {~/.dotfiles/,~/.}/tmux.conf

# Setup git
ln -sf {~/.dotfiles/,~/.}/gitconfig
ln -sf {~/.dotfiles/,~/.}/gitignore_global

# Setup hg
ln -sf {~/.dotfiles/,~/.}/hgignore_global
ln -sf {~/.dotfiles/,~/.}/hgrc

