#!/bin/bash

# Setup bash
ln -sf {~/.dotfiles/,~/.}bashrc
sudo ln -sf ~/.dotfiles/sys_bashrc /etc/bashrc

# Setup keys
sudo ln -sf ~/.dotfiles/sys_inputrc /etc/inputrc
mkdir -p ~/Library/KeyBindings/
ln -sf ~/.dotfiles/DefaultKeyBinding.dict ~/Library/KeyBindings/DefaultKeyBinding.dict

# Setup vim
mkdir -p ~/.vim
ln -sf {~/.dotfiles/,~/.}vimrc
ln -sf {~/.dotfiles/,~/.}gvimrc
ln -sf ~/.dotfiles/vim/* ~/.vim/

# Setup screen
sudo ln -sf ~/.dotfiles/sys_screenrc /etc/screenrc

# Setup tmux
ln -sf {~/.dotfiles/,~/.}tmux.conf

# Setup mutt
ln -sf {~/.dotfiles/,~/.}mutt
ln -sf {~/.dotfiles/,~/.}muttrc
ln -sf {~/.dotfiles/,~/.}offlineimaprc
ln -sf {~/.dotfiles/,~/.}msmtprc

# Setup urlview
ln -sf {~/.dotfiles/,~/.}urlview

# Setup git
ln -sf {~/.dotfiles/,~/.}gitconfig
ln -sf {~/.dotfiles/,~/.}gitignore_global

# Setup hg
ln -sf {~/.dotfiles/,~/.}hgignore_global
ln -sf {~/.dotfiles/,~/.}hgrc

