#!/bin/bash

# Setup bash
ln -sf {~/.dotfiles/,~/.}bashrc
ln -sf {~/.dotfiles/,~/.}bash_profile
sudo ln -sf ~/.dotfiles/sys_bashrc /etc/bashrc

# Setup keys
sudo ln -sf ~/.dotfiles/sys_inputrc /etc/inputrc
mkdir -p ~/Library/KeyBindings/
ln -sf ~/.dotfiles/DefaultKeyBinding.dict ~/Library/KeyBindings/DefaultKeyBinding.dict

# Setup vim
mkdir -p ~/.vim
mkdir -p ~/tmp/vim/{backup,swap,undo}
ln -sf {~/.dotfiles/,~/.}vimrc
ln -sf {~/.dotfiles/,~/.}gvimrc
ln -sf ~/.dotfiles/vim/* ~/.vim/

# Setup screen
sudo ln -sf ~/.dotfiles/sys_screenrc /etc/screenrc

# Setup tmux
ln -sf {~/.dotfiles/,~/.}tmux.conf

# Setup git
ln -sf {~/.dotfiles/,~/.}gitconfig
ln -sf {~/.dotfiles/,~/.}gitignore_global

# Setup hg
ln -sf {~/.dotfiles/,~/.}hgignore_global
ln -sf {~/.dotfiles/,~/.}hgrc

